# -*- coding: utf-8 -*-
"""Back Phone Usage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1whLAqYOh4khH-uVKdkvluA6roUJQi173
"""

import pandas as pd
import numpy as np
import datetime
from google.colab import files
#Import File
Raw_Data = pd.ExcelFile('Call Information Details Report.xlsx')
Data = pd.read_excel(Raw_Data, 'Call Information Details Report')
Data = Data.head(-4)
Data1 = Data[['Calling Number','Start Date','Duration']]
Data2 = Data[['Called Number','Start Date','Duration']]
Data1.rename(columns={'Calling Number':'Called Number'},inplace=True)
Final_Data = pd.concat([Data1,Data2],ignore_index=True)
Final_Data['Called Number'] = Final_Data['Called Number'].astype(str).replace('\.0','',regex=True)
Final_Data = Final_Data[pd.to_numeric(Final_Data['Called Number'], errors='coerce').notnull()]
Final_Data['Called Number'] = Final_Data['Called Number'].astype(float)
Final_Data['Start Date']= pd.to_datetime(Final_Data['Start Date'])
Final_Data['Month_Year'] = Final_Data['Start Date'].dt.to_period('M')
Final_Data = Final_Data[['Called Number','Month_Year']]
Final_Data['N'] = 1
Final_Data = pd.pivot_table(Final_Data,values='N',index=['Called Number'],columns=['Month_Year'],aggfunc='sum',margins=True, margins_name='Grand Total')
# Final_Data = Final_Data.groupby(['Called Number','Start Date']).size().reset_index(name='N')
Final_Data = Final_Data.fillna(0)
# Final_Data = Final_Data.reset_index(drop=True)
Final_Data['Avg_Usage']=Final_Data['Grand Total']/80
Final_Data['Avg_Usage']=Final_Data['Avg_Usage'].apply(lambda x:round(x,2))
# Final_Data= Final_Data.sort_values(by=['Avg_Usage'],ascending=False)
Final_Data = Final_Data.iloc[:-1].sort_values(by = ["Avg_Usage"], ascending = False)
Final_Data.rename(columns={'Called Number':'Phone Number'},inplace=True)
# Final_Data.to_excel('output.xlsx', encoding = 'utf-8-sig',index=False) 
Final_Data.to_excel('output.xlsx', encoding = 'utf-8-sig',index=True) 
files.download('output.xlsx')